# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI_Mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QLabel, QLineEdit, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QStackedWidget,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 800)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(800, 800))
        MainWindow.setMaximumSize(QSize(800, 800))
        icon = QIcon()
        icon.addFile(u"../icons/logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pb_Schnittstellen = QPushButton(self.centralwidget)
        self.pb_Schnittstellen.setObjectName(u"pb_Schnittstellen")
        self.pb_Schnittstellen.setGeometry(QRect(30, 100, 131, 41))
        self.pb_Schnittstellen.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"	color: rgb(255,255,255);\n"
"	background-color: rgb(68, 68, 68);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: rgb(0, 0, 0);\n"
"	color: rgb(255, 255, 255);\n"
"	border-radius: 10px;\n"
"}")
        self.pb_SoO = QPushButton(self.centralwidget)
        self.pb_SoO.setObjectName(u"pb_SoO")
        self.pb_SoO.setGeometry(QRect(30, 150, 131, 41))
        self.pb_SoO.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"	color: rgb(255,255,255);\n"
"	background-color: rgb(68, 68, 68);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: rgb(0, 0, 0);\n"
"	color: rgb(255, 255, 255);\n"
"	border-radius: 10px;\n"
"}")
        self.pb_spare = QPushButton(self.centralwidget)
        self.pb_spare.setObjectName(u"pb_spare")
        self.pb_spare.setGeometry(QRect(30, 200, 121, 41))
        self.pb_spare.setStyleSheet(u"QPushButton {\n"
"	color: rgb(255, 255, 255);\n"
"	background-color: rgb(45, 45, 45);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"	color: rgb(255,255,255);\n"
"	background-color: rgb(68, 68, 68);\n"
"	border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: rgb(0, 0, 0);\n"
"	color: rgb(255, 255, 255);\n"
"	border-radius: 10px;\n"
"}")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 10, 191, 771))
        self.widget.setStyleSheet(u"background-color: rgb(35, 35, 35);\n"
"border-radius: 25px;")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 686, 191, 41))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"background-color: rgb(255, 255, 0);\n"
"border-radius: 0px;")
        self.label.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.label_7 = QLabel(self.widget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(6, 730, 31, 20))
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.sw_nav_bar = QStackedWidget(self.centralwidget)
        self.sw_nav_bar.setObjectName(u"sw_nav_bar")
        self.sw_nav_bar.setEnabled(True)
        self.sw_nav_bar.setGeometry(QRect(220, 10, 571, 771))
        font1 = QFont()
        font1.setKerning(True)
        self.sw_nav_bar.setFont(font1)
        self.Interlocks = QWidget()
        self.Interlocks.setObjectName(u"Interlocks")
        self.label1 = QLabel(self.Interlocks)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 70, 49, 16))
        font2 = QFont()
        font2.setBold(True)
        font2.setKerning(True)
        self.label1.setFont(font2)
        self.label_2 = QLabel(self.Interlocks)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 100, 49, 16))
        self.label_2.setFont(font2)
        self.label_3 = QLabel(self.Interlocks)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 130, 49, 16))
        self.label_3.setFont(font2)
        self.label_4 = QLabel(self.Interlocks)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 190, 49, 16))
        self.label_4.setFont(font2)
        self.label_5 = QLabel(self.Interlocks)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 220, 61, 16))
        self.label_5.setFont(font2)
        self.le_fn_number = QLineEdit(self.Interlocks)
        self.le_fn_number.setObjectName(u"le_fn_number")
        self.le_fn_number.setGeometry(QRect(150, 70, 113, 22))
        self.le_customer = QLineEdit(self.Interlocks)
        self.le_customer.setObjectName(u"le_customer")
        self.le_customer.setGeometry(QRect(150, 100, 201, 22))
        self.le_firstname = QLineEdit(self.Interlocks)
        self.le_firstname.setObjectName(u"le_firstname")
        self.le_firstname.setGeometry(QRect(150, 130, 201, 22))
        self.le_lastname = QLineEdit(self.Interlocks)
        self.le_lastname.setObjectName(u"le_lastname")
        self.le_lastname.setGeometry(QRect(360, 130, 191, 22))
        self.cob_typ = QComboBox(self.Interlocks)
        self.cob_typ.addItem("")
        self.cob_typ.addItem("")
        self.cob_typ.addItem("")
        self.cob_typ.setObjectName(u"cob_typ")
        self.cob_typ.setGeometry(QRect(150, 190, 91, 22))
        self.cob_hardware = QComboBox(self.Interlocks)
        self.cob_hardware.addItem("")
        self.cob_hardware.addItem("")
        self.cob_hardware.addItem("")
        self.cob_hardware.setObjectName(u"cob_hardware")
        self.cob_hardware.setGeometry(QRect(150, 220, 91, 22))
        self.lb_interlock_length = QLabel(self.Interlocks)
        self.lb_interlock_length.setObjectName(u"lb_interlock_length")
        self.lb_interlock_length.setGeometry(QRect(10, 250, 131, 16))
        self.lb_interlock_length.setFont(font2)
        self.cob_interlock_length = QComboBox(self.Interlocks)
        self.cob_interlock_length.addItem("")
        self.cob_interlock_length.addItem("")
        self.cob_interlock_length.setObjectName(u"cob_interlock_length")
        self.cob_interlock_length.setGeometry(QRect(150, 250, 51, 22))
        self.pb_start = QPushButton(self.Interlocks)
        self.pb_start.setObjectName(u"pb_start")
        self.pb_start.setEnabled(True)
        self.pb_start.setGeometry(QRect(10, 320, 131, 51))
        self.label_10 = QLabel(self.Interlocks)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 280, 61, 16))
        self.label_10.setFont(font2)
        self.cob_language = QComboBox(self.Interlocks)
        self.cob_language.addItem("")
        self.cob_language.setObjectName(u"cob_language")
        self.cob_language.setGeometry(QRect(150, 280, 69, 22))
        self.le_email = QLineEdit(self.Interlocks)
        self.le_email.setObjectName(u"le_email")
        self.le_email.setGeometry(QRect(150, 160, 261, 22))
        self.label_15 = QLabel(self.Interlocks)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 10, 430, 50))
        font3 = QFont()
        font3.setPointSize(25)
        font3.setBold(True)
        font3.setKerning(True)
        self.label_15.setFont(font3)
        self.label_15.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lb_error = QLabel(self.Interlocks)
        self.lb_error.setObjectName(u"lb_error")
        self.lb_error.setGeometry(QRect(160, 360, 381, 91))
        self.lb_error.setFont(font2)
        self.lb_error.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.lb_error.setWordWrap(True)
        self.le_project_name = QLineEdit(self.Interlocks)
        self.le_project_name.setObjectName(u"le_project_name")
        self.le_project_name.setGeometry(QRect(270, 70, 113, 22))
        self.label_6 = QLabel(self.Interlocks)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(418, 206, 50, 51))
        self.label_6.setFont(font2)
        self.cob_harting = QComboBox(self.Interlocks)
        self.cob_harting.addItem("")
        self.cob_harting.setObjectName(u"cob_harting")
        self.cob_harting.setGeometry(QRect(473, 220, 61, 22))
        self.le_phone = QLineEdit(self.Interlocks)
        self.le_phone.setObjectName(u"le_phone")
        self.le_phone.setGeometry(QRect(420, 160, 131, 22))
        self.label_8 = QLabel(self.Interlocks)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(270, 220, 41, 21))
        self.label_8.setFont(font2)
        self.cob_safety = QComboBox(self.Interlocks)
        self.cob_safety.addItem("")
        self.cob_safety.addItem("")
        self.cob_safety.setObjectName(u"cob_safety")
        self.cob_safety.setGeometry(QRect(315, 220, 71, 22))
        self.sw_nav_bar.addWidget(self.Interlocks)
        self.SoO = QWidget()
        self.SoO.setObjectName(u"SoO")
        self.label_16 = QLabel(self.SoO)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(50, 10, 430, 50))
        self.label_16.setFont(font3)
        self.label_16.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.stackedWidget = QStackedWidget(self.SoO)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 160, 571, 621))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.scrollArea = QScrollArea(self.page_2)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(0, 20, 551, 581))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMinimumSize(QSize(0, 0))
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 532, 1618))
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 1600))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label1_3 = QLabel(self.frame)
        self.label1_3.setObjectName(u"label1_3")
        self.label1_3.setGeometry(QRect(13, 146, 141, 16))
        self.label1_3.setFont(font2)
        self.le_fn_number_3 = QLineEdit(self.frame)
        self.le_fn_number_3.setObjectName(u"le_fn_number_3")
        self.le_fn_number_3.setGeometry(QRect(190, 142, 51, 20))
        self.label1_4 = QLabel(self.frame)
        self.label1_4.setObjectName(u"label1_4")
        self.label1_4.setGeometry(QRect(13, 180, 141, 16))
        self.label1_4.setFont(font2)
        self.label1_5 = QLabel(self.frame)
        self.label1_5.setObjectName(u"label1_5")
        self.label1_5.setGeometry(QRect(189, 180, 81, 16))
        font4 = QFont()
        font4.setBold(False)
        font4.setKerning(True)
        self.label1_5.setFont(font4)
        self.label1_6 = QLabel(self.frame)
        self.label1_6.setObjectName(u"label1_6")
        self.label1_6.setGeometry(QRect(319, 180, 81, 16))
        self.label1_6.setFont(font4)
        self.label1_7 = QLabel(self.frame)
        self.label1_7.setObjectName(u"label1_7")
        self.label1_7.setGeometry(QRect(189, 200, 211, 16))
        self.label1_7.setFont(font4)
        self.checkBox = QCheckBox(self.frame)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(269, 179, 21, 20))
        self.checkBox_2 = QCheckBox(self.frame)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(399, 180, 21, 20))
        self.checkBox_3 = QCheckBox(self.frame)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(399, 200, 21, 20))
        self.label1_8 = QLabel(self.frame)
        self.label1_8.setObjectName(u"label1_8")
        self.label1_8.setGeometry(QRect(10, 10, 171, 16))
        self.label1_8.setFont(font2)
        self.label1_9 = QLabel(self.frame)
        self.label1_9.setObjectName(u"label1_9")
        self.label1_9.setGeometry(QRect(190, 10, 141, 16))
        self.label1_9.setFont(font4)
        self.checkBox_4 = QCheckBox(self.frame)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(290, 7, 21, 20))
        self.label1_10 = QLabel(self.frame)
        self.label1_10.setObjectName(u"label1_10")
        self.label1_10.setGeometry(QRect(190, 33, 141, 16))
        self.label1_10.setFont(font4)
        self.checkBox_5 = QCheckBox(self.frame)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(290, 30, 21, 20))
        self.checkBox_6 = QCheckBox(self.frame)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(290, 52, 21, 20))
        self.label1_11 = QLabel(self.frame)
        self.label1_11.setObjectName(u"label1_11")
        self.label1_11.setGeometry(QRect(190, 55, 101, 16))
        self.label1_11.setFont(font4)
        self.label1_12 = QLabel(self.frame)
        self.label1_12.setObjectName(u"label1_12")
        self.label1_12.setGeometry(QRect(14, 250, 141, 16))
        self.label1_12.setFont(font2)
        self.checkBox_7 = QCheckBox(self.frame)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(253, 250, 21, 20))
        self.label1_13 = QLabel(self.frame)
        self.label1_13.setObjectName(u"label1_13")
        self.label1_13.setGeometry(QRect(190, 250, 61, 16))
        self.label1_13.setFont(font4)
        self.le_fn_number_4 = QLineEdit(self.frame)
        self.le_fn_number_4.setObjectName(u"le_fn_number_4")
        self.le_fn_number_4.setGeometry(QRect(290, 250, 151, 20))
        self.label1_14 = QLabel(self.frame)
        self.label1_14.setObjectName(u"label1_14")
        self.label1_14.setGeometry(QRect(15, 290, 141, 16))
        self.label1_14.setFont(font2)
        self.label1_15 = QLabel(self.frame)
        self.label1_15.setObjectName(u"label1_15")
        self.label1_15.setGeometry(QRect(190, 290, 81, 16))
        self.label1_15.setFont(font4)
        self.checkBox_8 = QCheckBox(self.frame)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(253, 290, 21, 20))
        self.line = QFrame(self.frame)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 130, 491, 16))
        self.line.setFrameShadow(QFrame.Shadow.Raised)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.label1_16 = QLabel(self.frame)
        self.label1_16.setObjectName(u"label1_16")
        self.label1_16.setGeometry(QRect(10, 120, 201, 16))
        self.label1_16.setFont(font2)
        self.label1_17 = QLabel(self.frame)
        self.label1_17.setObjectName(u"label1_17")
        self.label1_17.setGeometry(QRect(16, 330, 141, 16))
        self.label1_17.setFont(font2)
        self.le_fn_number_5 = QLineEdit(self.frame)
        self.le_fn_number_5.setObjectName(u"le_fn_number_5")
        self.le_fn_number_5.setGeometry(QRect(190, 324, 311, 20))
        self.label1_18 = QLabel(self.frame)
        self.label1_18.setObjectName(u"label1_18")
        self.label1_18.setGeometry(QRect(10, 380, 201, 16))
        self.label1_18.setFont(font2)
        self.line_2 = QFrame(self.frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 390, 491, 16))
        self.line_2.setFrameShadow(QFrame.Shadow.Raised)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.label1_19 = QLabel(self.frame)
        self.label1_19.setObjectName(u"label1_19")
        self.label1_19.setGeometry(QRect(16, 410, 141, 16))
        self.label1_19.setFont(font2)
        self.label1_20 = QLabel(self.frame)
        self.label1_20.setObjectName(u"label1_20")
        self.label1_20.setGeometry(QRect(190, 411, 51, 16))
        self.label1_20.setFont(font4)
        self.checkBox_9 = QCheckBox(self.frame)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(360, 411, 21, 20))
        self.label1_21 = QLabel(self.frame)
        self.label1_21.setObjectName(u"label1_21")
        self.label1_21.setGeometry(QRect(320, 411, 81, 16))
        self.label1_21.setFont(font4)
        self.checkBox_10 = QCheckBox(self.frame)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(253, 410, 21, 20))
        self.label1_22 = QLabel(self.frame)
        self.label1_22.setObjectName(u"label1_22")
        self.label1_22.setGeometry(QRect(16, 438, 141, 16))
        self.label1_22.setFont(font2)
        self.checkBox_11 = QCheckBox(self.frame)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(253, 440, 21, 20))
        self.label1_23 = QLabel(self.frame)
        self.label1_23.setObjectName(u"label1_23")
        self.label1_23.setGeometry(QRect(190, 440, 81, 16))
        self.label1_23.setFont(font4)
        self.label1_24 = QLabel(self.frame)
        self.label1_24.setObjectName(u"label1_24")
        self.label1_24.setGeometry(QRect(16, 476, 141, 16))
        self.label1_24.setFont(font2)
        self.le_fn_number_6 = QLineEdit(self.frame)
        self.le_fn_number_6.setObjectName(u"le_fn_number_6")
        self.le_fn_number_6.setGeometry(QRect(190, 470, 311, 20))
        self.le_fn_number_7 = QLineEdit(self.frame)
        self.le_fn_number_7.setObjectName(u"le_fn_number_7")
        self.le_fn_number_7.setGeometry(QRect(300, 440, 151, 20))
        self.label1_25 = QLabel(self.frame)
        self.label1_25.setObjectName(u"label1_25")
        self.label1_25.setGeometry(QRect(16, 560, 141, 16))
        self.label1_25.setFont(font2)
        self.label1_27 = QLabel(self.frame)
        self.label1_27.setObjectName(u"label1_27")
        self.label1_27.setGeometry(QRect(10, 530, 201, 16))
        self.label1_27.setFont(font2)
        self.line_3 = QFrame(self.frame)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 540, 491, 16))
        self.line_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.cob_typ_3 = QComboBox(self.frame)
        self.cob_typ_3.addItem("")
        self.cob_typ_3.addItem("")
        self.cob_typ_3.addItem("")
        self.cob_typ_3.setObjectName(u"cob_typ_3")
        self.cob_typ_3.setGeometry(QRect(190, 560, 91, 22))
        self.label1_26 = QLabel(self.frame)
        self.label1_26.setObjectName(u"label1_26")
        self.label1_26.setGeometry(QRect(15, 597, 141, 16))
        self.label1_26.setFont(font2)
        self.label1_28 = QLabel(self.frame)
        self.label1_28.setObjectName(u"label1_28")
        self.label1_28.setGeometry(QRect(194, 600, 211, 16))
        self.label1_28.setFont(font4)
        self.label1_29 = QLabel(self.frame)
        self.label1_29.setObjectName(u"label1_29")
        self.label1_29.setGeometry(QRect(16, 631, 141, 16))
        self.label1_29.setFont(font2)
        self.checkBox_12 = QCheckBox(self.frame)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(364, 630, 21, 20))
        self.label1_30 = QLabel(self.frame)
        self.label1_30.setObjectName(u"label1_30")
        self.label1_30.setGeometry(QRect(193, 631, 151, 16))
        self.label1_30.setFont(font4)
        self.checkBox_13 = QCheckBox(self.frame)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(364, 653, 21, 20))
        self.label1_31 = QLabel(self.frame)
        self.label1_31.setObjectName(u"label1_31")
        self.label1_31.setGeometry(QRect(196, 654, 151, 16))
        self.label1_31.setFont(font4)
        self.label1_32 = QLabel(self.frame)
        self.label1_32.setObjectName(u"label1_32")
        self.label1_32.setGeometry(QRect(20, 690, 141, 16))
        self.label1_32.setFont(font2)
        self.checkBox_14 = QCheckBox(self.frame)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(263, 709, 21, 20))
        self.label1_33 = QLabel(self.frame)
        self.label1_33.setObjectName(u"label1_33")
        self.label1_33.setGeometry(QRect(196, 710, 51, 16))
        self.label1_33.setFont(font4)
        self.label1_34 = QLabel(self.frame)
        self.label1_34.setObjectName(u"label1_34")
        self.label1_34.setGeometry(QRect(300, 710, 111, 16))
        self.label1_34.setFont(font4)
        self.checkBox_15 = QCheckBox(self.frame)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setGeometry(QRect(410, 710, 21, 20))
        self.checkBox_16 = QCheckBox(self.frame)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(263, 690, 21, 20))
        self.label1_35 = QLabel(self.frame)
        self.label1_35.setObjectName(u"label1_35")
        self.label1_35.setGeometry(QRect(196, 690, 61, 16))
        self.label1_35.setFont(font4)
        self.checkBox_17 = QCheckBox(self.frame)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setGeometry(QRect(430, 750, 21, 20))
        self.label1_37 = QLabel(self.frame)
        self.label1_37.setObjectName(u"label1_37")
        self.label1_37.setGeometry(QRect(195, 750, 61, 16))
        self.label1_37.setFont(font4)
        self.label1_38 = QLabel(self.frame)
        self.label1_38.setObjectName(u"label1_38")
        self.label1_38.setGeometry(QRect(300, 750, 131, 16))
        self.label1_38.setFont(font4)
        self.label1_39 = QLabel(self.frame)
        self.label1_39.setObjectName(u"label1_39")
        self.label1_39.setGeometry(QRect(17, 750, 141, 16))
        self.label1_39.setFont(font2)
        self.checkBox_19 = QCheckBox(self.frame)
        self.checkBox_19.setObjectName(u"checkBox_19")
        self.checkBox_19.setGeometry(QRect(260, 750, 21, 20))
        self.label1_36 = QLabel(self.frame)
        self.label1_36.setObjectName(u"label1_36")
        self.label1_36.setGeometry(QRect(10, 870, 201, 16))
        self.label1_36.setFont(font2)
        self.line_4 = QFrame(self.frame)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(10, 880, 491, 16))
        self.line_4.setFrameShadow(QFrame.Shadow.Raised)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.label1_40 = QLabel(self.frame)
        self.label1_40.setObjectName(u"label1_40")
        self.label1_40.setGeometry(QRect(16, 786, 141, 16))
        self.label1_40.setFont(font2)
        self.le_fn_number_8 = QLineEdit(self.frame)
        self.le_fn_number_8.setObjectName(u"le_fn_number_8")
        self.le_fn_number_8.setGeometry(QRect(190, 780, 311, 20))
        self.label1_41 = QLabel(self.frame)
        self.label1_41.setObjectName(u"label1_41")
        self.label1_41.setGeometry(QRect(17, 910, 141, 16))
        self.label1_41.setFont(font2)
        self.label1_42 = QLabel(self.frame)
        self.label1_42.setObjectName(u"label1_42")
        self.label1_42.setGeometry(QRect(195, 910, 61, 16))
        self.label1_42.setFont(font4)
        self.checkBox_20 = QCheckBox(self.frame)
        self.checkBox_20.setObjectName(u"checkBox_20")
        self.checkBox_20.setGeometry(QRect(260, 910, 21, 20))
        self.label1_43 = QLabel(self.frame)
        self.label1_43.setObjectName(u"label1_43")
        self.label1_43.setGeometry(QRect(17, 940, 161, 16))
        self.label1_43.setFont(font2)
        self.label1_44 = QLabel(self.frame)
        self.label1_44.setObjectName(u"label1_44")
        self.label1_44.setGeometry(QRect(195, 940, 61, 16))
        self.label1_44.setFont(font4)
        self.checkBox_21 = QCheckBox(self.frame)
        self.checkBox_21.setObjectName(u"checkBox_21")
        self.checkBox_21.setGeometry(QRect(260, 940, 21, 20))
        self.label1_45 = QLabel(self.frame)
        self.label1_45.setObjectName(u"label1_45")
        self.label1_45.setGeometry(QRect(20, 970, 161, 16))
        self.label1_45.setFont(font2)
        self.label1_48 = QLabel(self.frame)
        self.label1_48.setObjectName(u"label1_48")
        self.label1_48.setGeometry(QRect(195, 970, 61, 16))
        self.label1_48.setFont(font4)
        self.checkBox_23 = QCheckBox(self.frame)
        self.checkBox_23.setObjectName(u"checkBox_23")
        self.checkBox_23.setGeometry(QRect(260, 970, 21, 20))
        self.cob_typ_4 = QComboBox(self.frame)
        self.cob_typ_4.addItem("")
        self.cob_typ_4.addItem("")
        self.cob_typ_4.setObjectName(u"cob_typ_4")
        self.cob_typ_4.setGeometry(QRect(320, 970, 141, 22))
        self.label1_46 = QLabel(self.frame)
        self.label1_46.setObjectName(u"label1_46")
        self.label1_46.setGeometry(QRect(20, 1000, 161, 16))
        self.label1_46.setFont(font2)
        self.label1_47 = QLabel(self.frame)
        self.label1_47.setObjectName(u"label1_47")
        self.label1_47.setGeometry(QRect(195, 1000, 61, 16))
        self.label1_47.setFont(font4)
        self.checkBox_22 = QCheckBox(self.frame)
        self.checkBox_22.setObjectName(u"checkBox_22")
        self.checkBox_22.setGeometry(QRect(260, 1000, 21, 20))
        self.line_5 = QFrame(self.frame)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 1100, 491, 16))
        self.line_5.setFrameShadow(QFrame.Shadow.Raised)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.label1_49 = QLabel(self.frame)
        self.label1_49.setObjectName(u"label1_49")
        self.label1_49.setGeometry(QRect(10, 1090, 201, 16))
        self.label1_49.setFont(font2)
        self.label1_50 = QLabel(self.frame)
        self.label1_50.setObjectName(u"label1_50")
        self.label1_50.setGeometry(QRect(16, 1036, 141, 16))
        self.label1_50.setFont(font2)
        self.le_fn_number_9 = QLineEdit(self.frame)
        self.le_fn_number_9.setObjectName(u"le_fn_number_9")
        self.le_fn_number_9.setGeometry(QRect(190, 1030, 311, 20))
        self.label1_51 = QLabel(self.frame)
        self.label1_51.setObjectName(u"label1_51")
        self.label1_51.setGeometry(QRect(17, 1130, 141, 16))
        self.label1_51.setFont(font2)
        self.label1_52 = QLabel(self.frame)
        self.label1_52.setObjectName(u"label1_52")
        self.label1_52.setGeometry(QRect(195, 1130, 61, 16))
        self.label1_52.setFont(font4)
        self.checkBox_24 = QCheckBox(self.frame)
        self.checkBox_24.setObjectName(u"checkBox_24")
        self.checkBox_24.setGeometry(QRect(260, 1130, 21, 20))
        self.checkBox_25 = QCheckBox(self.frame)
        self.checkBox_25.setObjectName(u"checkBox_25")
        self.checkBox_25.setGeometry(QRect(380, 1150, 21, 20))
        self.label1_53 = QLabel(self.frame)
        self.label1_53.setObjectName(u"label1_53")
        self.label1_53.setGeometry(QRect(190, 1150, 191, 16))
        self.label1_53.setFont(font4)
        self.label1_54 = QLabel(self.frame)
        self.label1_54.setObjectName(u"label1_54")
        self.label1_54.setGeometry(QRect(20, 1180, 141, 16))
        self.label1_54.setFont(font2)
        self.checkBox_26 = QCheckBox(self.frame)
        self.checkBox_26.setObjectName(u"checkBox_26")
        self.checkBox_26.setGeometry(QRect(255, 1180, 21, 20))
        self.label1_55 = QLabel(self.frame)
        self.label1_55.setObjectName(u"label1_55")
        self.label1_55.setGeometry(QRect(190, 1180, 61, 16))
        self.label1_55.setFont(font4)
        self.le_fn_number_10 = QLineEdit(self.frame)
        self.le_fn_number_10.setObjectName(u"le_fn_number_10")
        self.le_fn_number_10.setGeometry(QRect(194, 1214, 311, 20))
        self.label1_56 = QLabel(self.frame)
        self.label1_56.setObjectName(u"label1_56")
        self.label1_56.setGeometry(QRect(20, 1220, 141, 16))
        self.label1_56.setFont(font2)
        self.label1_57 = QLabel(self.frame)
        self.label1_57.setObjectName(u"label1_57")
        self.label1_57.setGeometry(QRect(10, 1280, 201, 16))
        self.label1_57.setFont(font2)
        self.line_6 = QFrame(self.frame)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(10, 1290, 491, 16))
        self.line_6.setFrameShadow(QFrame.Shadow.Raised)
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.label1_58 = QLabel(self.frame)
        self.label1_58.setObjectName(u"label1_58")
        self.label1_58.setGeometry(QRect(17, 1320, 171, 16))
        self.label1_58.setFont(font2)
        self.checkBox_27 = QCheckBox(self.frame)
        self.checkBox_27.setObjectName(u"checkBox_27")
        self.checkBox_27.setGeometry(QRect(255, 1320, 21, 20))
        self.label1_59 = QLabel(self.frame)
        self.label1_59.setObjectName(u"label1_59")
        self.label1_59.setGeometry(QRect(190, 1320, 61, 16))
        self.label1_59.setFont(font4)
        self.cob_typ_5 = QComboBox(self.frame)
        self.cob_typ_5.addItem("")
        self.cob_typ_5.addItem("")
        self.cob_typ_5.addItem("")
        self.cob_typ_5.setObjectName(u"cob_typ_5")
        self.cob_typ_5.setGeometry(QRect(310, 1320, 141, 22))
        self.label1_60 = QLabel(self.frame)
        self.label1_60.setObjectName(u"label1_60")
        self.label1_60.setGeometry(QRect(17, 1350, 171, 16))
        self.label1_60.setFont(font2)
        self.checkBox_28 = QCheckBox(self.frame)
        self.checkBox_28.setObjectName(u"checkBox_28")
        self.checkBox_28.setGeometry(QRect(255, 1350, 21, 20))
        self.label1_61 = QLabel(self.frame)
        self.label1_61.setObjectName(u"label1_61")
        self.label1_61.setGeometry(QRect(190, 1350, 61, 16))
        self.label1_61.setFont(font4)
        self.label1_62 = QLabel(self.frame)
        self.label1_62.setObjectName(u"label1_62")
        self.label1_62.setGeometry(QRect(20, 1380, 171, 16))
        self.label1_62.setFont(font2)
        self.label1_63 = QLabel(self.frame)
        self.label1_63.setObjectName(u"label1_63")
        self.label1_63.setGeometry(QRect(185, 1380, 61, 16))
        self.label1_63.setFont(font4)
        self.checkBox_29 = QCheckBox(self.frame)
        self.checkBox_29.setObjectName(u"checkBox_29")
        self.checkBox_29.setGeometry(QRect(250, 1380, 21, 20))
        self.le_fn_number_11 = QLineEdit(self.frame)
        self.le_fn_number_11.setObjectName(u"le_fn_number_11")
        self.le_fn_number_11.setGeometry(QRect(194, 1404, 311, 20))
        self.label1_64 = QLabel(self.frame)
        self.label1_64.setObjectName(u"label1_64")
        self.label1_64.setGeometry(QRect(20, 1410, 141, 16))
        self.label1_64.setFont(font2)

        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_2)
        self.le_fn_number_2 = QLineEdit(self.SoO)
        self.le_fn_number_2.setObjectName(u"le_fn_number_2")
        self.le_fn_number_2.setGeometry(QRect(160, 70, 113, 22))
        self.label_9 = QLabel(self.SoO)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 140, 49, 16))
        self.label_9.setFont(font2)
        self.label_11 = QLabel(self.SoO)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 100, 49, 16))
        self.label_11.setFont(font2)
        self.label1_2 = QLabel(self.SoO)
        self.label1_2.setObjectName(u"label1_2")
        self.label1_2.setGeometry(QRect(20, 70, 49, 16))
        self.label1_2.setFont(font2)
        self.le_customer_2 = QLineEdit(self.SoO)
        self.le_customer_2.setObjectName(u"le_customer_2")
        self.le_customer_2.setGeometry(QRect(160, 100, 201, 22))
        self.cob_typ_2 = QComboBox(self.SoO)
        self.cob_typ_2.addItem("")
        self.cob_typ_2.addItem("")
        self.cob_typ_2.addItem("")
        self.cob_typ_2.setObjectName(u"cob_typ_2")
        self.cob_typ_2.setGeometry(QRect(160, 140, 91, 22))
        self.le_project_name_2 = QLineEdit(self.SoO)
        self.le_project_name_2.setObjectName(u"le_project_name_2")
        self.le_project_name_2.setGeometry(QRect(280, 70, 113, 22))
        self.sw_nav_bar.addWidget(self.SoO)
        self.spare = QWidget()
        self.spare.setObjectName(u"spare")
        self.label_13 = QLabel(self.spare)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(120, 120, 341, 161))
        font5 = QFont()
        font5.setPointSize(20)
        font5.setKerning(True)
        self.label_13.setFont(font5)
        self.label_17 = QLabel(self.spare)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(50, 10, 430, 50))
        self.label_17.setFont(font3)
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.sw_nav_bar.addWidget(self.spare)
        MainWindow.setCentralWidget(self.centralwidget)
        self.widget.raise_()
        self.pb_Schnittstellen.raise_()
        self.pb_SoO.raise_()
        self.pb_spare.raise_()
        self.sw_nav_bar.raise_()
        QWidget.setTabOrder(self.pb_Schnittstellen, self.pb_SoO)
        QWidget.setTabOrder(self.pb_SoO, self.pb_spare)
        QWidget.setTabOrder(self.pb_spare, self.le_fn_number)
        QWidget.setTabOrder(self.le_fn_number, self.le_customer)
        QWidget.setTabOrder(self.le_customer, self.le_firstname)
        QWidget.setTabOrder(self.le_firstname, self.le_lastname)
        QWidget.setTabOrder(self.le_lastname, self.cob_typ)
        QWidget.setTabOrder(self.cob_typ, self.cob_hardware)
        QWidget.setTabOrder(self.cob_hardware, self.cob_interlock_length)
        QWidget.setTabOrder(self.cob_interlock_length, self.pb_start)
        QWidget.setTabOrder(self.pb_start, self.cob_language)
        QWidget.setTabOrder(self.cob_language, self.le_email)
        QWidget.setTabOrder(self.le_email, self.le_project_name)
        QWidget.setTabOrder(self.le_project_name, self.cob_harting)
        QWidget.setTabOrder(self.cob_harting, self.le_phone)
        QWidget.setTabOrder(self.le_phone, self.cob_safety)
        QWidget.setTabOrder(self.cob_safety, self.le_fn_number_2)
        QWidget.setTabOrder(self.le_fn_number_2, self.le_project_name_2)
        QWidget.setTabOrder(self.le_project_name_2, self.le_customer_2)
        QWidget.setTabOrder(self.le_customer_2, self.cob_typ_2)
        QWidget.setTabOrder(self.cob_typ_2, self.scrollArea)
        QWidget.setTabOrder(self.scrollArea, self.le_fn_number_3)
        QWidget.setTabOrder(self.le_fn_number_3, self.checkBox)
        QWidget.setTabOrder(self.checkBox, self.checkBox_2)
        QWidget.setTabOrder(self.checkBox_2, self.checkBox_3)

        self.retranslateUi(MainWindow)

        self.sw_nav_bar.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"BaseDocGenerator", None))
        self.pb_Schnittstellen.setText(QCoreApplication.translate("MainWindow", u"Schnittstellen", None))
        self.pb_SoO.setText(QCoreApplication.translate("MainWindow", u"SoO", None))
        self.pb_spare.setText(QCoreApplication.translate("MainWindow", u"spare", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt;\">LIEBHERR</span></p></body></html>", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>v0.0</p></body></html>", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"Projekt", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Kunde", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Kontakt", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Anlage", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Hardware", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number.setPlaceholderText(QCoreApplication.translate("MainWindow", u"FN-Nummer", None))
        self.le_customer.setPlaceholderText(QCoreApplication.translate("MainWindow", u"z.B. Mercedes-Benz AG", None))
        self.le_firstname.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Vorname", None))
        self.le_lastname.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Nachname", None))
        self.cob_typ.setItemText(0, QCoreApplication.translate("MainWindow", u"ladeportal", None))
        self.cob_typ.setItemText(1, QCoreApplication.translate("MainWindow", u"phs", None))
        self.cob_typ.setItemText(2, QCoreApplication.translate("MainWindow", u"roboter", None))

        self.cob_hardware.setItemText(0, QCoreApplication.translate("MainWindow", u"profinet", None))
        self.cob_hardware.setItemText(1, QCoreApplication.translate("MainWindow", u"profibus", None))
        self.cob_hardware.setItemText(2, QCoreApplication.translate("MainWindow", u"hardwired", None))

        self.lb_interlock_length.setText(QCoreApplication.translate("MainWindow", u"L\u00e4nge Interlock in Byte", None))
        self.cob_interlock_length.setItemText(0, QCoreApplication.translate("MainWindow", u"32", None))
        self.cob_interlock_length.setItemText(1, QCoreApplication.translate("MainWindow", u"64", None))

        self.pb_start.setText(QCoreApplication.translate("MainWindow", u"Generiere Dokument", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Sprache", None))
        self.cob_language.setItemText(0, QCoreApplication.translate("MainWindow", u"Deutsch", None))

        self.le_email.setPlaceholderText(QCoreApplication.translate("MainWindow", u"E-Mail", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Schnittstellenbeschreibung", None))
        self.lb_error.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.le_project_name.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_project_name.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Projekt Name", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">zus\u00e4tzl. </p>\n"
"<p style=\" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Harting</p></body></html>", None))
        self.cob_harting.setItemText(0, QCoreApplication.translate("MainWindow", u"Ja", None))

        self.le_phone.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Telefon", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Safety", None))
        self.cob_safety.setItemText(0, QCoreApplication.translate("MainWindow", u"24-pol", None))
        self.cob_safety.setItemText(1, QCoreApplication.translate("MainWindow", u"Profisafe", None))

        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Systembeschreibung", None))
        self.label1_3.setText(QCoreApplication.translate("MainWindow", u"Anzahl der Operationen", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_3.setText("")
        self.le_fn_number_3.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Num", None))
        self.label1_4.setText(QCoreApplication.translate("MainWindow", u"Ben\u00f6tigte Laufwagen", None))
        self.label1_5.setText(QCoreApplication.translate("MainWindow", u"H-Laufwagen", None))
        self.label1_6.setText(QCoreApplication.translate("MainWindow", u"I-Laufwagen", None))
        self.label1_7.setText(QCoreApplication.translate("MainWindow", u"mehrere Laufwagen bei min. einer OP", None))
        self.checkBox.setText("")
        self.checkBox_2.setText("")
        self.checkBox_3.setText("")
        self.label1_8.setText(QCoreApplication.translate("MainWindow", u"Definitionen in SoO", None))
        self.label1_9.setText(QCoreApplication.translate("MainWindow", u"Rohteil/Fertigteil", None))
        self.checkBox_4.setText("")
        self.label1_10.setText(QCoreApplication.translate("MainWindow", u"Zelle/Linie", None))
        self.checkBox_5.setText("")
        self.checkBox_6.setText(QCoreApplication.translate("MainWindow", u"Befestigungstypen", None))
        self.label1_11.setText(QCoreApplication.translate("MainWindow", u"Befestigungstypen", None))
        self.label1_12.setText(QCoreApplication.translate("MainWindow", u"Leitrechner", None))
        self.checkBox_7.setText("")
        self.label1_13.setText(QCoreApplication.translate("MainWindow", u"vorhanden", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_4.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_4.setText("")
        self.le_fn_number_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Name des Systems", None))
        self.label1_14.setText(QCoreApplication.translate("MainWindow", u"Energieeinsparung", None))
        self.label1_15.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_8.setText("")
        self.label1_16.setText(QCoreApplication.translate("MainWindow", u"GENERELLE INFORMATIONEN", None))
        self.label1_17.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_5.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_5.setText("")
        self.le_fn_number_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
        self.label1_18.setText(QCoreApplication.translate("MainWindow", u"TEILE INFORMATIONEN", None))
        self.label1_19.setText(QCoreApplication.translate("MainWindow", u"Identifikation der Teile", None))
        self.label1_20.setText(QCoreApplication.translate("MainWindow", u"Kamera", None))
        self.checkBox_9.setText("")
        self.label1_21.setText(QCoreApplication.translate("MainWindow", u"RFID", None))
        self.checkBox_10.setText("")
        self.label1_22.setText(QCoreApplication.translate("MainWindow", u"Verfolgbarkeit", None))
        self.checkBox_11.setText("")
        self.label1_23.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.label1_24.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_6.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_6.setText("")
        self.le_fn_number_6.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_7.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_7.setText("")
        self.le_fn_number_7.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Name des Systems", None))
        self.label1_25.setText(QCoreApplication.translate("MainWindow", u"Betriebsfunktionen", None))
        self.label1_27.setText(QCoreApplication.translate("MainWindow", u"BASIS FUNKTIONEN", None))
        self.cob_typ_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Daimler", None))
        self.cob_typ_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Ford", None))
        self.cob_typ_3.setItemText(2, QCoreApplication.translate("MainWindow", u"Allgemein", None))

        self.label1_26.setText(QCoreApplication.translate("MainWindow", u"Halt nach Taktende", None))
        self.label1_28.setText(QCoreApplication.translate("MainWindow", u"Halt nach Taktende in Service Position", None))
        self.label1_29.setText(QCoreApplication.translate("MainWindow", u"L\u00e4ngenkompensation", None))
        self.checkBox_12.setText(QCoreApplication.translate("MainWindow", u"Temperaturkompensation", None))
        self.label1_30.setText(QCoreApplication.translate("MainWindow", u"Temperaturkompensation", None))
        self.checkBox_13.setText(QCoreApplication.translate("MainWindow", u"zus\u00e4tzliche Kompensation", None))
        self.label1_31.setText(QCoreApplication.translate("MainWindow", u"zus\u00e4tzliche Kompensation", None))
        self.label1_32.setText(QCoreApplication.translate("MainWindow", u"Stacklight", None))
        self.checkBox_14.setText(QCoreApplication.translate("MainWindow", u"mit Horn", None))
        self.label1_33.setText(QCoreApplication.translate("MainWindow", u"mit Horn", None))
        self.label1_34.setText(QCoreApplication.translate("MainWindow", u"mit Zusatzfunktion", None))
        self.checkBox_15.setText(QCoreApplication.translate("MainWindow", u"mit Horn", None))
        self.checkBox_16.setText("")
        self.label1_35.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_17.setText(QCoreApplication.translate("MainWindow", u"mit Horn", None))
        self.label1_37.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.label1_38.setText(QCoreApplication.translate("MainWindow", u"in Safety eingebunden", None))
        self.label1_39.setText(QCoreApplication.translate("MainWindow", u"Sumpfpumpe", None))
        self.checkBox_19.setText("")
        self.label1_36.setText(QCoreApplication.translate("MainWindow", u"MASCHINEN FUNKTIONEN", None))
        self.label1_40.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_8.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_8.setText("")
        self.le_fn_number_8.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
        self.label1_41.setText(QCoreApplication.translate("MainWindow", u"Vorpositionen", None))
        self.label1_42.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_20.setText("")
        self.label1_43.setText(QCoreApplication.translate("MainWindow", u"Seat-Check in der Maschine", None))
        self.label1_44.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_21.setText("")
        self.label1_45.setText(QCoreApplication.translate("MainWindow", u"Ladeluken", None))
        self.label1_48.setText(QCoreApplication.translate("MainWindow", u"vorhanden", None))
        self.checkBox_23.setText("")
        self.cob_typ_4.setItemText(0, QCoreApplication.translate("MainWindow", u"von uns gesteuert", None))
        self.cob_typ_4.setItemText(1, QCoreApplication.translate("MainWindow", u"von Maschine gesteuert", None))

        self.label1_46.setText(QCoreApplication.translate("MainWindow", u"Chip-Dump", None))
        self.label1_47.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_22.setText("")
        self.label1_49.setText(QCoreApplication.translate("MainWindow", u"WEITERE FUNKTIONEN", None))
        self.label1_50.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_9.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_9.setText("")
        self.le_fn_number_9.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
        self.label1_51.setText(QCoreApplication.translate("MainWindow", u"SPC-Platz", None))
        self.label1_52.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_24.setText("")
        self.checkBox_25.setText("")
        self.label1_53.setText(QCoreApplication.translate("MainWindow", u"mit Inspection-Counter-Handling", None))
        self.label1_54.setText(QCoreApplication.translate("MainWindow", u"Cell-Master", None))
        self.checkBox_26.setText("")
        self.label1_55.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_10.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_10.setText("")
        self.le_fn_number_10.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
        self.label1_56.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
        self.label1_57.setText(QCoreApplication.translate("MainWindow", u"SCHNITTSTELLEN SYSTEME", None))
        self.label1_58.setText(QCoreApplication.translate("MainWindow", u"Signalaustausch Safety", None))
        self.checkBox_27.setText(QCoreApplication.translate("MainWindow", u"Signalaustausch Safety", None))
        self.label1_59.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.cob_typ_5.setItemText(0, QCoreApplication.translate("MainWindow", u"Kunde", None))
        self.cob_typ_5.setItemText(1, QCoreApplication.translate("MainWindow", u"Liebherr", None))
        self.cob_typ_5.setItemText(2, QCoreApplication.translate("MainWindow", u"Kombination", None))

        self.label1_60.setText(QCoreApplication.translate("MainWindow", u"Anbindung ans Firmennetz", None))
        self.checkBox_28.setText(QCoreApplication.translate("MainWindow", u"Signalaustausch Safety", None))
        self.label1_61.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.label1_62.setText(QCoreApplication.translate("MainWindow", u"Ferndiagnose (VPN)", None))
        self.label1_63.setText(QCoreApplication.translate("MainWindow", u"ben\u00f6tigt", None))
        self.checkBox_29.setText(QCoreApplication.translate("MainWindow", u"Signalaustausch Safety", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_11.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_11.setText("")
        self.le_fn_number_11.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Kundenw\u00fcnsche / weitere Kundenanforderungen", None))
        self.label1_64.setText(QCoreApplication.translate("MainWindow", u"Sonstiges", None))
#if QT_CONFIG(tooltip)
        self.le_fn_number_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_fn_number_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"FN-Nummer", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Anlage", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Kunde", None))
        self.label1_2.setText(QCoreApplication.translate("MainWindow", u"Projekt", None))
        self.le_customer_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"z.B. Mercedes-Benz AG", None))
        self.cob_typ_2.setItemText(0, QCoreApplication.translate("MainWindow", u"ladeportal", None))
        self.cob_typ_2.setItemText(1, QCoreApplication.translate("MainWindow", u"phs", None))
        self.cob_typ_2.setItemText(2, QCoreApplication.translate("MainWindow", u"roboter", None))

#if QT_CONFIG(tooltip)
        self.le_project_name_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.le_project_name_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Projekt Name", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"not programmed yet", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"spare", None))
    # retranslateUi

